// Auth
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

// Children
export const CHILDREN_REQUEST = 'CHILDREN_REQUEST'
export const CHILDREN_SUCCESS = 'CHILDREN_SUCCESS'
export const CHILDREN_FAILURE = 'CHILDREN_FAILURE'
export const CHILD_FETCH_SUCCESS = 'CHILD_FETCH_SUCCESS'
export const CHILD_DELETE_SUCCESS = 'CHILD_DELETE_SUCCESS'

// Artworks
export const ARTWORKS_REQUEST = 'ARTWORKS_REQUEST'
export const ARTWORKS_SUCCESS = 'ARTWORKS_SUCCESS'
export const ARTWORKS_FAILURE = 'ARTWORKS_FAILURE'
export const ARTWORK_FETCH_SUCCESS = 'ARTWORK_FETCH_SUCCESS'
export const ARTWORK_DELETE_SUCCESS = 'ARTWORK_DELETE_SUCCESS'
